version: "3.8"
services:

  db:
    image: postgres:latest
    environment:
      POSTGRES_USER_FILE: /run/secrets/POSTGRES_USER
      POSTGRES_PASSWORD_FILE: /run/secrets/POSTGRES_PASSWORD
      POSTGRES_DB_FILE: /run/secrets/POSTGRES_DB
    volumes:
      - db-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 60s
    deploy:
      replicas: 1
      placement:
        constraints: [ node.role == manager ]
      update_config:
        failure_action: rollback
    secrets:
      - POSTGRES_PASSWORD
      - POSTGRES_USER
      - POSTGRES_DB

  app:
    image: registry.gitlab.com/rminix/flask_quotes:app_latest
    ports:
      - "8080"
    environment:
      POSTGRES_USER: /run/secrets/POSTGRES_USER
      POSTGRES_PASSWORD: /run/secrets/POSTGRES_PASSWORD
      POSTGRES_DB: /run/secrets/POSTGRES_DB
      SECRET_KEY: /run/secrets/SECRET_KEY
      FLASK_ENV: production
      POSTGRES_HOST: db
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
      update_config:
        failure_action: rollback
        order: start-first
    secrets:
      - POSTGRES_PASSWORD
      - POSTGRES_USER
      - POSTGRES_DB
      - SECRET_KEY


  nginx:
    image: nginx:stable-alpine
    ports:
      - target: 80
        published: 80
        protocol: tcp
        mode: host
      - target: 443
        published: 443
        protocol: tcp
        mode: host
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    volumes:
      - /etc/letsencrypt/:/etc/letsencrypt/
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/rminix.ir.conf:/etc/nginx/conf.d/default.conf
      - nginx_log:/var/log/nginx




volumes:
  db-data:
  nginx_log:

configs:
  nginx_config:
    file: ./nginx/nginx.conf

secrets:
  POSTGRES_PASSWORD:
    file: ./secrets/POSTGRES_PASSWORD
  POSTGRES_USER:
    file: ./secrets/POSTGRES_USER
  POSTGRES_DB:
    file: ./secrets/POSTGRES_DB
  SECRET_KEY:
    file: ./secrets/SECRET_KEY
